# Generated by Django 2.2.9 on 2021-11-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211103_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
