# Generated by Django 2.2.9 on 2021-11-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211103_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
